apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-test
  description: Python app that displays time - named python-test
  annotations:
    github.com/project-slug: rupa-2/python-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
