site_name: 'python-test'
site_description: 'Main documentation for the python-test'
repo_url: https://github.com/rupa2/python-test
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
